---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

workspace:
  path: /go/src/github.com/UKHomeOffice/docker-kuberang

steps:
- name: build_smoketest
  pull: if-not-exists
  image: golang:1.9.1
  commands:
  - curl -L https://github.com/Masterminds/glide/releases/download/v0.13.0/glide-v0.13.0-linux-amd64.tar.gz -o - | tar -xzf -
  - linux-amd64/glide install
  - go build -ldflags "-X main.Version=$${DRONE_COMMIT}" -o bin/smoketest
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux

- name: build_docker_image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker build -t kuberang:$${DRONE_COMMIT_SHA} .
  when:
    event:
      exclude:
      - tag

- name: scan
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/anchore-submission:latest
  environment:
    IMAGE_NAME: kuberang:${DRONE_COMMIT_SHA}
    LOCAL_IMAGE: true
  when:
    event:
      exclude:
      - tag

- name: image_to_ecr
  image: plugins/ecr
  environment:
    AWS_REGION: eu-west-2
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    repo: acp/kuberang
    registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
    tags:
      - ${DRONE_TAG}
  when:
    event:
    - tag

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  when:
    event:
      exclude:
      - tag

- name: anchore-submission-server
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission
  commands:
  - /run.sh server
  when:
    event:
      exclude:
      - tag
...
